const data = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiction",
  },
  { title: "1984", author: "George Orwell", category: "Dystopian" },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Classic",
  },
  {
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    category: "Magical Realism",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Romance",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Fiction",
  },
  { title: "The Hobbit", author: "J.R.R. Tolkien", category: "Fantasy" },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    category: "Dystopian",
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    category: "Fantasy",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Dystopian",
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Adventure",
  },
  {
    title: "Animal Farm",
    author: "George Orwell",
    category: "Political Satire",
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    category: "Mystery",
  },
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    category: "Mystery",
  },
  {
    title: "The Fault in Our Stars",
    author: "John Green",
    category: "Young Adult",
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    category: "Fantasy",
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    category: "Fiction",
  },
  { title: "Life of Pi", author: "Yann Martel", category: "Adventure" },
  {
    title: "The Road",
    author: "Cormac McCarthy",
    category: "Post-Apocalyptic",
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    category: "Classic",
  },
  { title: "Gone Girl", author: "Gillian Flynn", category: "Thriller" },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    category: "Dystopian",
  },
  {
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    category: "Fantasy",
  },
  {
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    category: "Historical Fiction",
  },
  {
    title: "Wuthering Heights",
    author: "Emily Brontë",
    category: "Classic",
  },
  { title: "The Catch-22", author: "Joseph Heller", category: "Satire" },
  { title: "The Bell Jar", author: "Sylvia Plath", category: "Fiction" },
  {
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    category: "Historical Fiction",
  },
  {
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    category: "Children's",
  },
  { title: "The Shining", author: "Stephen King", category: "Horror" },
  {
    title: "Little Women",
    author: "Louisa May Alcott",
    category: "Classic",
  },
  {
    title: "The Outsiders",
    author: "S.E. Hinton",
    category: "Young Adult",
  },
  {
    title: "The Sun Also Rises",
    author: "Ernest Hemingway",
    category: "Fiction",
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    category: "Science Fiction",
  },
  {
    title: "The Road Less Traveled",
    author: "M. Scott Peck",
    category: "Self-Help",
  },
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    category: "Biography",
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    category: "Biography",
  },
  {
    title: "The Lovely Bones",
    author: "Alice Sebold",
    category: "Fiction",
  },
  {
    title: "A Clockwork Orange",
    author: "Anthony Burgess",
    category: "Dystopian",
  },
  { title: "The Alchemist", author: "Paulo Coelho", category: "Fiction" },
  { title: "The Art of War", author: "Sun Tzu", category: "Philosophy" },
  {
    title: "The Color Purple",
    author: "Alice Walker",
    category: "Fiction",
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    category: "Science Fiction",
  },
  { title: "The Road", author: "Cormac McCarthy", category: "Fiction" },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    category: "Adventure",
  },
  {
    title: "Freakonomics",
    author: "Steven D. Levitt",
    category: "Non-Fiction",
  },
  { title: "The Godfather", author: "Mario Puzo", category: "Crime" },
  {
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    category: "Fiction",
  },
  { title: "Me Before You", author: "Jojo Moyes", category: "Romance" },
  {
    title: "The Woman in the Window",
    author: "A.J. Finn",
    category: "Thriller",
  },
  {
    title: "The Help",
    author: "Kathryn Stockett",
    category: "Historical Fiction",
  },
  {
    title: "The Martian",
    author: "Andy Weir",
    category: "Science Fiction",
  },
  {
    title: "The Night Circus",
    author: "Erin Morgenstern",
    category: "Fantasy",
  },
  {
    title: "Big Little Lies",
    author: "Liane Moriarty",
    category: "Fiction",
  },
  { title: "Educated", author: "Tara Westover", category: "Biography" },
  { title: "Dune", author: "Frank Herbert", category: "Science Fiction" },
  {
    title: "The Great Alone",
    author: "Kristin Hannah",
    category: "Historical Fiction",
  },
  {
    title: "An American Marriage",
    author: "Tayari Jones",
    category: "Fiction",
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    category: "Thriller",
  },
  { title: "Circe", author: "Madeline Miller", category: "Fantasy" },
  { title: "Normal People", author: "Sally Rooney", category: "Fiction" },
  {
    title: "The Vanishing Half",
    author: "Brit Bennett",
    category: "Fiction",
  },
  {
    title: "The Henna Artist",
    author: "Alka Joshi",
    category: "Historical Fiction",
  },
  {
    title: "The Song of Achilles",
    author: "Madeline Miller",
    category: "Fantasy",
  },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    category: "Historical Fiction",
  },
  {
    title: "The Nightingale",
    author: "Kristin Hannah",
    category: "Historical Fiction",
  },
  {
    title: "Pachinko",
    author: "Min Jin Lee",
    category: "Historical Fiction",
  },
  {
    title: "A Man Called Ove",
    author: "Fredrik Backman",
    category: "Fiction",
  },
  {
    title: "The Water Dancer",
    author: "Ta-Nehisi Coates",
    category: "Historical Fiction",
  },
  {
    title: "Before the Coffee Gets Cold",
    author: "Toshikazu Kawaguchi",
    category: "Fiction",
  },
  {
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Fiction",
  },
  {
    title: "The 5 AM Club",
    author: "Robin Sharma",
    category: "Self-Help",
  },
  { title: "The Guest List", author: "Lucy Foley", category: "Thriller" },
  {
    title: "The Paris Library",
    author: "Janet Skeslien Charles",
    category: "Historical Fiction",
  },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    category: "Fantasy",
  },
  {
    title: "The Silent Corner",
    author: "Dean Koontz",
    category: "Thriller",
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    category: "Fiction",
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
  },
  { title: "Born a Crime", author: "Trevor Noah", category: "Biography" },
  {
    title: "The Diary of a Bookseller",
    author: "Shaun Bythell",
    category: "Non-Fiction",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self-Help",
  },
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    category: "Self-Help",
  },
  {
    title: "The Secret History",
    author: "Donna Tartt",
    category: "Mystery",
  },
  {
    title: "The Time Traveler's Wife",
    author: "Audrey Niffenegger",
    category: "Romance",
  },
  {
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    category: "Thriller",
  },
  {
    title: "The Lovely Bones",
    author: "Alice Sebold",
    category: "Fiction",
  },
  {
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    category: "Mystery",
  },
  {
    title: "The Girl with the Louding Voice",
    author: "Abi Daré",
    category: "Fiction",
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    category: "Fiction",
  },
  {
    title: "Big Little Lies",
    author: "Liane Moriarty",
    category: "Fiction",
  },
  { title: "The Giver", author: "Lois Lowry", category: "Dystopian" },
  {
    title: "All the Light We Cannot See",
    author: "Anthony Doerr",
    category: "Historical Fiction",
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    category: "Thriller",
  },
  {
    title: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    category: "Historical Fiction",
  },
  {
    title: "Eleanor Oliphant Is Completely Fine",
    author: "Gail Honeyman",
    category: "Fiction",
  },
  { title: "Room", author: "Emma Donoghue", category: "Fiction" },
  {
    title: "The Fault in Our Stars",
    author: "John Green",
    category: "Young Adult",
  },
  {
    title: "The Underground Railroad",
    author: "Colson Whitehead",
    category: "Historical Fiction",
  },
  {
    title: "The Immortalists",
    author: "Chloe Benjamin",
    category: "Fiction",
  },
  {
    title: "The Night Circus",
    author: "Erin Morgenstern",
    category: "Fantasy",
  },
  { title: "Circe", author: "Madeline Miller", category: "Fantasy" },
  {
    title: "Pachinko",
    author: "Min Jin Lee",
    category: "Historical Fiction",
  },
  {
    title: "Homegoing",
    author: "Yaa Gyasi",
    category: "Historical Fiction",
  },
  {
    title: "The Light We Lost",
    author: "Jill Santopolo",
    category: "Fiction",
  },
  {
    title: "Before We Were Strangers",
    author: "Renée Carlino",
    category: "Romance",
  },
  {
    title: "The Rosie Project",
    author: "Graeme Simsion",
    category: "Romance",
  },
  {
    title: "The Cuckoo's Calling",
    author: "Robert Galbraith",
    category: "Mystery",
  },
  {
    title: "The Paris Wife",
    author: "Paula McLain",
    category: "Historical Fiction",
  },
  {
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    category: "Fiction",
  },
  {
    title: "Little Fires Everywhere",
    author: "Celeste Ng",
    category: "Fiction",
  },
  {
    title: "The Overstory",
    author: "Richard Powers",
    category: "Fiction",
  },
  {
    title: "The Orphan Master's Son",
    author: "Adam Johnson",
    category: "Fiction",
  },
  {
    title: "The Power",
    author: "Naomi Alderman",
    category: "Science Fiction",
  },
  {
    title: "The Nightingale",
    author: "Kristin Hannah",
    category: "Historical Fiction",
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    category: "Fiction",
  },
  { title: "Normal People", author: "Sally Rooney", category: "Fiction" },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    category: "Historical Fiction",
  },
  {
    title: "The Woman in the Window",
    author: "A.J. Finn",
    category: "Thriller",
  },
  {
    title: "A Man Called Ove",
    author: "Fredrik Backman",
    category: "Fiction",
  },
  {
    title: "Station Eleven",
    author: "Emily St. John Mandel",
    category: "Science Fiction",
  },
  { title: "Educated", author: "Tara Westover", category: "Biography" },
  {
    title: "The Tattooist of Auschwitz",
    author: "Heather Morris",
    category: "Historical Fiction",
  },
  {
    title: "The Girl with the Louding Voice",
    author: "Abi Daré",
    category: "Fiction",
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    category: "Biography",
  },
  {
    title: "The Art of Racing in the Rain",
    author: "Garth Stein",
    category: "Fiction",
  },
  {
    title: "The Light Between Oceans",
    author: "M.L. Stedman",
    category: "Historical Fiction",
  },
  {
    title: "The Ocean at the End of the Lane",
    author: "Neil Gaiman",
    category: "Fantasy",
  },
  {
    title: "The Secret Keeper",
    author: "Kate Morton",
    category: "Historical Fiction",
  },
  {
    title: "Anxious People",
    author: "Fredrik Backman",
    category: "Fiction",
  },
  {
    title: "The Dutch House",
    author: "Ann Patchett",
    category: "Fiction",
  },
  {
    title: "The Golem and the Jinni",
    author: "Helene Wecker",
    category: "Fantasy",
  },
  { title: "The Goldfinch", author: "Donna Tartt", category: "Fiction" },
  {
    title: "The 100-Year-Old Man Who Climbed Out the Window and Disappeared",
    author: "Jonas Jonasson",
    category: "Fiction",
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Non-Fiction",
  },
  {
    title: "Outliers",
    author: "Malcolm Gladwell",
    category: "Non-Fiction",
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    category: "Self-Help",
  },
  { title: "Born a Crime", author: "Trevor Noah", category: "Biography" },
  { title: "Educated", author: "Tara Westover", category: "Biography" },
  { title: "Becoming", author: "Michelle Obama", category: "Biography" },
  { title: "Bossypants", author: "Tina Fey", category: "Biography" },
  {
    title: "I Am Malala",
    author: "Malala Yousafzai",
    category: "Biography",
  },
  {
    title: "The Glass Castle",
    author: "Jeannette Walls",
    category: "Biography",
  },
  { title: "Wild", author: "Cheryl Strayed", category: "Biography" },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
  },
  {
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    category: "Self-Help",
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen Covey",
    category: "Self-Help",
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    category: "Self-Help",
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "Non-Fiction",
  },
  {
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    category: "Non-Fiction",
  },
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    category: "Self-Help",
  },
  {
    title: "The Five Love Languages",
    author: "Gary Chapman",
    category: "Self-Help",
  },
  { title: "The Alchemist", author: "Paulo Coelho", category: "Fiction" },
  {
    title: "Life Lessons",
    author: "Elisabeth Kübler-Ross",
    category: "Self-Help",
  },
  {
    title: "The Happiness Project",
    author: "Gretchen Rubin",
    category: "Self-Help",
  },
  {
    title: "The Gifts of Imperfection",
    author: "Brené Brown",
    category: "Self-Help",
  },
  {
    title: "Daring Greatly",
    author: "Brené Brown",
    category: "Self-Help",
  },
  {
    title: "Quiet: The Power of Introverts in a World That Can't Stop Talking",
    author: "Susan Cain",
    category: "Non-Fiction",
  },
  {
    title: "A Woman of No Importance",
    author: "Sonia Purnell",
    category: "Biography",
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    category: "Biography",
  },
  {
    title: "The Wright Brothers",
    author: "David McCullough",
    category: "Biography",
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    category: "Biography",
  },
  {
    title: "The Warmth of Other Suns",
    author: "Isabel Wilkerson",
    category: "Non-Fiction",
  },
  {
    title: "Freakonomics",
    author: "Steven D. Levitt",
    category: "Non-Fiction",
  },
  {
    title: "The Devil in the White City",
    author: "Erik Larson",
    category: "Non-Fiction",
  },
  {
    title: "The New Jim Crow",
    author: "Michelle Alexander",
    category: "Non-Fiction",
  },
  {
    title: "Just Mercy",
    author: "Bryan Stevenson",
    category: "Non-Fiction",
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    category: "Biography",
  },
  {
    title: "A People's History of the United States",
    author: "Howard Zinn",
    category: "Non-Fiction",
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    category: "Fiction",
  },
  {
    title: "A Little Life",
    author: "Hanya Yanagihara",
    category: "Fiction",
  },
  { title: "The Road", author: "Cormac McCarthy", category: "Fiction" },
  {
    title: "The Night Circus",
    author: "Erin Morgenstern",
    category: "Fantasy",
  },
  {
    title: "The Martian",
    author: "Andy Weir",
    category: "Science Fiction",
  },
  {
    title: "Cloud Atlas",
    author: "David Mitchell",
    category: "Science Fiction",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Dystopian",
  },
  { title: "1984", author: "George Orwell", category: "Dystopian" },
  {
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    category: "Dystopian",
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    category: "Science Fiction",
  },
  {
    title: "Neuromancer",
    author: "William Gibson",
    category: "Science Fiction",
  },
  {
    title: "The Dispossessed",
    author: "Ursula K. Le Guin",
    category: "Science Fiction",
  },
  {
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    category: "Science Fiction",
  },
  { title: "Dune", author: "Frank Herbert", category: "Science Fiction" },
  {
    title: "Snow Crash",
    author: "Neal Stephenson",
    category: "Science Fiction",
  },
  {
    title: "The Bone Clocks",
    author: "David Mitchell",
    category: "Fantasy",
  },
  {
    title: "Americanah",
    author: "Chimamanda Ngozi Adichie",
    category: "Fiction",
  },
  {
    title: "The Song of Achilles",
    author: "Madeline Miller",
    category: "Fantasy",
  },
  {
    title: "The Nightingale",
    author: "Kristin Hannah",
    category: "Historical Fiction",
  },
  {
    title: "Everything I Never Told You",
    author: "Celeste Ng",
    category: "Fiction",
  },
  {
    title: "The Heart's Invisible Furies",
    author: "John Boyne",
    category: "Fiction",
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    category: "Fiction",
  },
  {
    title: "The Vanishing Half",
    author: "Brit Bennett",
    category: "Fiction",
  },
  {
    title: "Red, White & Royal Blue",
    author: "Casey McQuiston",
    category: "Romance",
  },
  {
    title: "It Ends with Us",
    author: "Colleen Hoover",
    category: "Romance",
  },
  {
    title: "The Unhoneymooners",
    author: "Christina Lauren",
    category: "Romance",
  },
  { title: "Beach Read", author: "Emily Henry", category: "Romance" },
  {
    title: "The Hating Game",
    author: "Sally Thorne",
    category: "Romance",
  },
  {
    title: "People We Meet on Vacation",
    author: "Emily Henry",
    category: "Romance",
  },
  {
    title: "Love & Gelato",
    author: "Jenna Evans Welch",
    category: "Romance",
  },
  {
    title: "Maybe in Another Life",
    author: "Taylor Jenkins Reid",
    category: "Romance",
  },
  {
    title: "To All the Boys I've Loved Before",
    author: "Jenny Han",
    category: "Romance",
  },
  {
    title: "The Wedding Date",
    author: "Jasmine Guillory",
    category: "Romance",
  },
  { title: "The Ex Hex", author: "Erin Sterling", category: "Romance" },
  {
    title: "Love and Other Words",
    author: "Christina Lauren",
    category: "Romance",
  },
  {
    title: "The Kiss Quotient",
    author: "Helen Hoang",
    category: "Romance",
  },
  { title: "The Bride Test", author: "Helen Hoang", category: "Romance" },
  {
    title: "Twilight",
    author: "Stephenie Meyer",
    category: "Young Adult",
  },
  {
    title: "The Maze Runner",
    author: "James Dashner",
    category: "Young Adult",
  },
  {
    title: "Divergent",
    author: "Veronica Roth",
    category: "Young Adult",
  },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    category: "Young Adult",
  },
  {
    title: "City of Bones",
    author: "Cassandra Clare",
    category: "Fantasy",
  },
  {
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    category: "Fantasy",
  },
  {
    title: "An Ember in the Ashes",
    author: "Sabaa Tahir",
    category: "Fantasy",
  },
  {
    title: "Crescent City: House of Earth and Blood",
    author: "Sarah J. Maas",
    category: "Fantasy",
  },
  {
    title: "Serpent & Dove",
    author: "Shelby Mahurin",
    category: "Fantasy",
  },
  {
    title: "The Cruel Prince",
    author: "Holly Black",
    category: "Fantasy",
  },
  {
    title: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    category: "Fantasy",
  },
  { title: "Six of Crows", author: "Leigh Bardugo", category: "Fantasy" },
  {
    title: "The Bone Season",
    author: "Samantha Shannon",
    category: "Fantasy",
  },
  { title: "The Poppy War", author: "R.F. Kuang", category: "Fantasy" },
  {
    title: "The Gilded Wolves",
    author: "Roshani Chokshi",
    category: "Fantasy",
  },
  {
    title: "The Starless Sea",
    author: "Erin Morgenstern",
    category: "Fantasy",
  },
  {
    title: "A Darker Shade of Magic",
    author: "V.E. Schwab",
    category: "Fantasy",
  },
  {
    title: "A Gathering of Shadows",
    author: "V.E. Schwab",
    category: "Fantasy",
  },
  {
    title: "A Conjuring of Light",
    author: "V.E. Schwab",
    category: "Fantasy",
  },
  {
    title: "The City We Became",
    author: "N.K. Jemisin",
    category: "Fantasy",
  },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    category: "Fantasy",
  },
  {
    title: "Children of Blood and Bone",
    author: "Tomi Adeyemi",
    category: "Fantasy",
  },
  {
    title: "The Wrath and the Dawn",
    author: "Renée Ahdieh",
    category: "Fantasy",
  },
  {
    title: "Shadow and Bone",
    author: "Leigh Bardugo",
    category: "Fantasy",
  },
  {
    title: "We Hunt the Flame",
    author: "Hafsah Faizal",
    category: "Fantasy",
  },
  { title: "The Bone Witch", author: "Rin Chupeco", category: "Fantasy" },
  {
    title: "Skyward",
    author: "Brandon Sanderson",
    category: "Science Fiction",
  },
  {
    title: "Cinder",
    author: "Marissa Meyer",
    category: "Science Fiction",
  },
  {
    title: "Illuminae",
    author: "Amie Kaufman",
    category: "Science Fiction",
  },
  {
    title: "Gideon the Ninth",
    author: "Tamsyn Muir",
    category: "Fantasy",
  },
  {
    title: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    category: "Fantasy",
  },
  {
    title: "The Invisible Man",
    author: "H.G. Wells",
    category: "Science Fiction",
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    category: "Science Fiction",
  },
  {
    title: "The War of the Worlds",
    author: "H.G. Wells",
    category: "Science Fiction",
  },
  {
    title: "The Time Machine",
    author: "H.G. Wells",
    category: "Science Fiction",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Science Fiction",
  },
  {
    title: "The Martian Chronicles",
    author: "Ray Bradbury",
    category: "Science Fiction",
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    category: "Science Fiction",
  },
  { title: "1984", author: "George Orwell", category: "Science Fiction" },
  {
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    category: "Science Fiction",
  },
  {
    title: "The Dispossessed",
    author: "Ursula K. Le Guin",
    category: "Science Fiction",
  },
  { title: "Dune", author: "Frank Herbert", category: "Science Fiction" },
  {
    title: "Snow Crash",
    author: "Neal Stephenson",
    category: "Science Fiction",
  },
  {
    title: "Neuromancer",
    author: "William Gibson",
    category: "Science Fiction",
  },
  {
    title: "The Moon and Sixpence",
    author: "W. Somerset Maugham",
    category: "Fiction",
  },
  {
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    category: "Fiction",
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Fiction",
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiction",
  },
  { title: "The Bell Jar", author: "Sylvia Plath", category: "Fiction" },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Fiction",
  },
  { title: "Moby Dick", author: "Herman Melville", category: "Fiction" },
  { title: "War and Peace", author: "Leo Tolstoy", category: "Fiction" },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    category: "Fiction",
  },
  {
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    category: "Fiction",
  },
  {
    title: "Wuthering Heights",
    author: "Emily Brontë",
    category: "Fiction",
  },
  { title: "Jane Eyre", author: "Charlotte Brontë", category: "Fiction" },
  {
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    category: "Fiction",
  },
  {
    title: "Great Expectations",
    author: "Charles Dickens",
    category: "Fiction",
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    category: "Fiction",
  },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    category: "Fiction",
  },
  { title: "Les Misérables", author: "Victor Hugo", category: "Fiction" },
  {
    title: "The Phantom of the Opera",
    author: "Gaston Leroux",
    category: "Fiction",
  },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    category: "Dystopian",
  },
  { title: "The Road", author: "Cormac McCarthy", category: "Fiction" },
  {
    title: "The Brief Wondrous Life of Oscar Wao",
    author: "Junot Díaz",
    category: "Fiction",
  },
  {
    title: "The Amazing Adventures of Kavalier & Clay",
    author: "Michael Chabon",
    category: "Fiction",
  },
  { title: "The Goldfinch", author: "Donna Tartt", category: "Fiction" },
  { title: "Life of Pi", author: "Yann Martel", category: "Fiction" },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    category: "Fiction",
  },
  {
    title: "The Secret Life of Bees",
    author: "Sue Monk Kidd",
    category: "Fiction",
  },
  { title: "The Alchemist", author: "Paulo Coelho", category: "Fiction" },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    category: "Historical Fiction",
  },
  {
    title: "The Night Circus",
    author: "Erin Morgenstern",
    category: "Fantasy",
  },
  {
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    category: "Thriller",
  },
  { title: "Gone Girl", author: "Gillian Flynn", category: "Thriller" },
  {
    title: "The Woman in the Window",
    author: "A.J. Finn",
    category: "Thriller",
  },
  {
    title: "Before I Go to Sleep",
    author: "S.J. Watson",
    category: "Thriller",
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    category: "Thriller",
  },
  {
    title: "Big Little Lies",
    author: "Liane Moriarty",
    category: "Fiction",
  },
  {
    title: "The Wife Between Us",
    author: "Greer Hendricks",
    category: "Thriller",
  },
  {
    title: "The Other Woman",
    author: "Sandie Jones",
    category: "Thriller",
  },
  {
    title: "Behind Closed Doors",
    author: "B.A. Paris",
    category: "Thriller",
  },
  {
    title: "The Couple Next Door",
    author: "Shari Lapena",
    category: "Thriller",
  },
  {
    title: "An Anonymous Girl",
    author: "Greer Hendricks",
    category: "Thriller",
  },
  { title: "The Guest List", author: "Lucy Foley", category: "Thriller" },
  { title: "The Chain", author: "Adrian McKinty", category: "Thriller" },
  {
    title: "The Hunting Party",
    author: "Lucy Foley",
    category: "Thriller",
  },
  {
    title: "The Family Upstairs",
    author: "Lisa Jewell",
    category: "Thriller",
  },
  { title: "The Shadows", author: "Alex North", category: "Thriller" },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    category: "Thriller",
  },
  { title: "The Vanishing Half", author: "Brit Bennett", category: "Fiction" },
  {
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    category: "Fiction",
  },
  { title: "The Midnight Library", author: "Matt Haig", category: "Fantasy" },
  { title: "Anxious People", author: "Fredrik Backman", category: "Fiction" },
  { title: "The Guest List", author: "Lucy Foley", category: "Mystery" },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    category: "Fantasy",
  },
  {
    title: "Daisy Jones & The Six",
    author: "Taylor Jenkins Reid",
    category: "Fiction",
  },
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    category: "Science Fiction",
  },
  {
    title: "The Four Winds",
    author: "Kristin Hannah",
    category: "Historical Fiction",
  },
  {
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    category: "Science Fiction",
  },
  { title: "The Overstory", author: "Richard Powers", category: "Literature" },
  {
    title: "The Tattooist of Auschwitz",
    author: "Heather Morris",
    category: "Historical Fiction",
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    category: "Fiction",
  },
  { title: "Big Little Lies", author: "Liane Moriarty", category: "Fiction" },
  {
    title: "The Woman in the Window",
    author: "A.J. Finn",
    category: "Thriller",
  },
  { title: "Normal People", author: "Sally Rooney", category: "Literature" },
  { title: "Circe", author: "Madeline Miller", category: "Fantasy" },
  {
    title: "The Night Circus",
    author: "Erin Morgenstern",
    category: "Fantasy",
  },
  { title: "The Light We Lost", author: "Jill Santopolo", category: "Fiction" },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    category: "Historical Fiction",
  },
  { title: "Homegoing", author: "Yaa Gyasi", category: "Historical Fiction" },
  { title: "A Man Called Ove", author: "Fredrik Backman", category: "Fiction" },
  { title: "The Goldfinch", author: "Donna Tartt", category: "Literature" },
  { title: "The Alchemist", author: "Paulo Coelho", category: "Fiction" },
  {
    title: "The Song of Achilles",
    author: "Madeline Miller",
    category: "Fantasy",
  },
  {
    title: "Eleanor Oliphant Is Completely Fine",
    author: "Gail Honeyman",
    category: "Fiction",
  },
  { title: "The Silent Corner", author: "Dean Koontz", category: "Thriller" },
  { title: "Educated", author: "Tara Westover", category: "Memoir" },
  { title: "Becoming", author: "Michelle Obama", category: "Memoir" },
  {
    title: "The Giver of Stars",
    author: "Jojo Moyes",
    category: "Historical Fiction",
  },
  { title: "The Henna Artist", author: "Alka Joshi", category: "Fiction" },
  {
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    category: "Fantasy",
  },
  { title: "It Ends with Us", author: "Colleen Hoover", category: "Romance" },
  { title: "The City We Became", author: "N.K. Jemisin", category: "Fantasy" },
  {
    title: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    category: "Fantasy",
  },
  {
    title: "The Water Dancer",
    author: "Ta-Nehisi Coates",
    category: "Historical Fiction",
  },
  { title: "The 5 AM Club", author: "Robin Sharma", category: "Self-Help" },
  { title: "The Vanishing Half", author: "Brit Bennett", category: "Fiction" },
  {
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    category: "Psychology",
  },
  {
    title: "The Happiness Project",
    author: "Gretchen Rubin",
    category: "Self-Help",
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "Psychology",
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    category: "Self-Help",
  },
  { title: "Atomic Habits", author: "James Clear", category: "Self-Help" },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    category: "Self-Help",
  },
  { title: "Daring Greatly", author: "Brené Brown", category: "Self-Help" },
  { title: "You Are a Badass", author: "Jen Sincero", category: "Self-Help" },
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    category: "Self-Help",
  },
  {
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    category: "Non-Fiction",
  },
  { title: "The Lean Startup", author: "Eric Ries", category: "Business" },
  { title: "Good to Great", author: "Jim Collins", category: "Business" },
  {
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    category: "Finance",
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    category: "Finance",
  },
  {
    title: "The Total Money Makeover",
    author: "Dave Ramsey",
    category: "Finance",
  },
  { title: "The Barefoot Investor", author: "Scott Pape", category: "Finance" },
  {
    title: "The Millionaire Next Door",
    author: "Thomas J. Stanley",
    category: "Finance",
  },
  {
    title: "You Are a Badass at Making Money",
    author: "Jen Sincero",
    category: "Finance",
  },
  { title: "The 10X Rule", author: "Grant Cardone", category: "Business" },
  { title: "Start with Why", author: "Simon Sinek", category: "Business" },
  { title: "Crushing It!", author: "Gary Vaynerchuk", category: "Business" },
  { title: "The Art of War", author: "Sun Tzu", category: "Business" },
  {
    title: "The Innovator's Dilemma",
    author: "Clayton M. Christensen",
    category: "Business",
  },
  { title: "Made to Stick", author: "Chip Heath", category: "Business" },
  {
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    category: "Business",
  },
  {
    title: "The E-Myth Revisited",
    author: "Michael E. Gerber",
    category: "Business",
  },
  {
    title: "The 5 Love Languages",
    author: "Gary Chapman",
    category: "Self-Help",
  },
  { title: "Attached", author: "Amir Levine", category: "Self-Help" },
  {
    title: "Men Are from Mars, Women Are from Venus",
    author: "John Gray",
    category: "Self-Help",
  },
  {
    title: "The Gifts of Imperfection",
    author: "Brené Brown",
    category: "Self-Help",
  },
  { title: "Rising Strong", author: "Brené Brown", category: "Self-Help" },
  {
    title: "The Dance of Anger",
    author: "Harriet Lerner",
    category: "Self-Help",
  },
  {
    title: "The Emotion Code",
    author: "Bradley Nelson",
    category: "Self-Help",
  },
  { title: "Mindset", author: "Carol S. Dweck", category: "Psychology" },
  { title: "The Confidence Code", author: "Katty Kay", category: "Self-Help" },
  { title: "Grit", author: "Angela Duckworth", category: "Psychology" },
  { title: "Presence", author: "Amy Cuddy", category: "Self-Help" },
  {
    title: "The Gifts of Imperfection",
    author: "Brené Brown",
    category: "Self-Help",
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    category: "Self-Help",
  },
  {
    title: "How to Stop Worrying and Start Living",
    author: "Dale Carnegie",
    category: "Self-Help",
  },
  {
    title: "The Art of Happiness",
    author: "Dalai Lama",
    category: "Self-Help",
  },
  { title: "Outliers", author: "Malcolm Gladwell", category: "Non-Fiction" },
  {
    title: "The Tipping Point",
    author: "Malcolm Gladwell",
    category: "Non-Fiction",
  },
  { title: "Blink", author: "Malcolm Gladwell", category: "Non-Fiction" },
  {
    title: "What the Dog Saw",
    author: "Malcolm Gladwell",
    category: "Non-Fiction",
  },
  {
    title: "Freakonomics",
    author: "Steven D. Levitt",
    category: "Non-Fiction",
  },
  {
    title: "Super Freakonomics",
    author: "Steven D. Levitt",
    category: "Non-Fiction",
  },
  {
    title: "The Black Swan",
    author: "Nassim Nicholas Taleb",
    category: "Non-Fiction",
  },
  {
    title: "Antifragile",
    author: "Nassim Nicholas Taleb",
    category: "Non-Fiction",
  },
  {
    title: "The Art of Possibility",
    author: "Rosamund Stone Zander",
    category: "Non-Fiction",
  },
  { title: "The Lean Startup", author: "Eric Ries", category: "Business" },
  { title: "Good to Great", author: "Jim Collins", category: "Business" },
  { title: "Thinking in Bets", author: "Annie Duke", category: "Business" },
  { title: "Principles", author: "Ray Dalio", category: "Business" },
  {
    title: "Never Split the Difference",
    author: "Chris Voss",
    category: "Business",
  },
  { title: "The 4-Hour Workweek", author: "Tim Ferriss", category: "Business" },
  { title: "The Miracle Morning", author: "Hal Elrod", category: "Self-Help" },
  {
    title: "The Compound Effect",
    author: "Darren Hardy",
    category: "Self-Help",
  },
  { title: "The Power of Now", author: "Eckhart Tolle", category: "Self-Help" },
  {
    title: "The Untethered Soul",
    author: "Michael A. Singer",
    category: "Self-Help",
  },
  {
    title: "Awaken the Giant Within",
    author: "Tony Robbins",
    category: "Self-Help",
  },
  {
    title: "The Magic of Thinking Big",
    author: "David J. Schwartz",
    category: "Self-Help",
  },
  {
    title: "The Road Less Traveled",
    author: "M. Scott Peck",
    category: "Self-Help",
  },
  {
    title: "The Happiness Advantage",
    author: "Shawn Achor",
    category: "Self-Help",
  },
  { title: "The Art of War", author: "Sun Tzu", category: "Self-Help" },
  { title: "How to Be a 3% Man", author: "Corey Wayne", category: "Self-Help" },
  {
    title: "The Science of Getting Rich",
    author: "Wallace D. Wattles",
    category: "Self-Help",
  },
  { title: "The Secret", author: "Rhonda Byrne", category: "Self-Help" },
  {
    title: "The Law of Attraction",
    author: "Esther Hicks",
    category: "Self-Help",
  },
  { title: "The Book of Joy", author: "Dalai Lama", category: "Self-Help" },
  {
    title: "The Celestine Prophecy",
    author: "James Redfield",
    category: "Self-Help",
  },
  {
    title: "The Power of Intention",
    author: "Wayne Dyer",
    category: "Self-Help",
  },
  {
    title: "Awakening the Mind",
    author: "Henry Marshall",
    category: "Self-Help",
  },
  {
    title: "The Magic of Believing",
    author: "Claude M. Bristol",
    category: "Self-Help",
  },
  {
    title: "The Greatest Salesman in the World",
    author: "Og Mandino",
    category: "Self-Help",
  },
  {
    title: "The Seven Spiritual Laws of Success",
    author: "Deepak Chopra",
    category: "Self-Help",
  },
  {
    title: "The Way of the Superior Man",
    author: "David Deida",
    category: "Self-Help",
  },
  {
    title: "Feel the Fear and Do It Anyway",
    author: "Susan Jeffers",
    category: "Self-Help",
  },
  {
    title: "The Untethered Soul",
    author: "Michael A. Singer",
    category: "Self-Help",
  },
  {
    title: "The Gifts of Imperfection",
    author: "Brené Brown",
    category: "Self-Help",
  },
  { title: "The Alchemist", author: "Paulo Coelho", category: "Fiction" },
  {
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    category: "Self-Help",
  },
  {
    title: "The Magic of Thinking Big",
    author: "David J. Schwartz",
    category: "Self-Help",
  },
  {
    title: "You Can Heal Your Life",
    author: "Louise Hay",
    category: "Self-Help",
  },
  {
    title: "Braving the Wilderness",
    author: "Brené Brown",
    category: "Self-Help",
  },
  {
    title: "The Art of Happiness",
    author: "Dalai Lama",
    category: "Self-Help",
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    category: "Self-Help",
  },
  {
    title: "The Success Principles",
    author: "Jack Canfield",
    category: "Self-Help",
  },
  { title: "The Power of Now", author: "Eckhart Tolle", category: "Self-Help" },
  {
    title: "The Law of Attraction",
    author: "Esther Hicks",
    category: "Self-Help",
  },
  { title: "The Secret", author: "Rhonda Byrne", category: "Self-Help" },
  {
    title: "A Course in Miracles",
    author: "Foundation for Inner Peace",
    category: "Self-Help",
  },
  {
    title: "Conversations with God",
    author: "Neale Donald Walsch",
    category: "Self-Help",
  },
  { title: "The Art of Living", author: "Epictetus", category: "Self-Help" },
  {
    title: "The Way of the Peaceful Warrior",
    author: "Dan Millman",
    category: "Self-Help",
  },
  {
    title: "The Four Agreements",
    author: "Don Miguel Ruiz",
    category: "Self-Help",
  },
  {
    title: "The Power of Vulnerability",
    author: "Brené Brown",
    category: "Self-Help",
  },
  {
    title: "The Compound Effect",
    author: "Darren Hardy",
    category: "Self-Help",
  },
  {
    title: "The Power of Intention",
    author: "Wayne Dyer",
    category: "Self-Help",
  },
  {
    title: "The 5 Love Languages",
    author: "Gary Chapman",
    category: "Self-Help",
  },
  {
    title: "The 4-Hour Workweek",
    author: "Tim Ferriss",
    category: "Self-Help",
  },
  {
    title: "The Secret of Success",
    author: "Nido Qubein",
    category: "Self-Help",
  },
  { title: "Dare to Lead", author: "Brené Brown", category: "Self-Help" },
  { title: "The Miracle Morning", author: "Hal Elrod", category: "Self-Help" },
  {
    title: "The Happiness Project",
    author: "Gretchen Rubin",
    category: "Self-Help",
  },
  { title: "Big Magic", author: "Elizabeth Gilbert", category: "Self-Help" },
  { title: "The Art of Living", author: "Epictetus", category: "Self-Help" },
  { title: "Atomic Habits", author: "James Clear", category: "Self-Help" },
  { title: "Mindfulness", author: "Mark Williams", category: "Self-Help" },
  { title: "Eat Pray Love", author: "Elizabeth Gilbert", category: "Memoir" },
  { title: "The Glass Castle", author: "Jeannette Walls", category: "Memoir" },
  { title: "Wild", author: "Cheryl Strayed", category: "Memoir" },
  { title: "Educated", author: "Tara Westover", category: "Memoir" },
  { title: "Becoming", author: "Michelle Obama", category: "Memoir" },
  {
    title: "When Breath Becomes Air",
    author: "Paul Kalanithi",
    category: "Memoir",
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    category: "Non-Fiction",
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
  },
  { title: "Educated", author: "Tara Westover", category: "Non-Fiction" },
  {
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    category: "Non-Fiction",
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    category: "Non-Fiction",
  },
  { title: "Atomic Habits", author: "James Clear", category: "Non-Fiction" },
  {
    title: "The Life-Changing Magic of Tidying Up",
    author: "Marie Kondo",
    category: "Non-Fiction",
  },
  { title: "Why We Sleep", author: "Matthew Walker", category: "Non-Fiction" },
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    category: "Self-Help",
  },
  {
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    category: "Self-Help",
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    category: "Self-Help",
  },
  { title: "You Are a Badass", author: "Jen Sincero", category: "Self-Help" },
  {
    title: "The Happiness Advantage",
    author: "Shawn Achor",
    category: "Self-Help",
  },
  { title: "The Art of War", author: "Sun Tzu", category: "Self-Help" },
  { title: "The Alchemist", author: "Paulo Coelho", category: "Fiction" },
  { title: "Pride and Prejudice", author: "Jane Austen", category: "Fiction" },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
  },
  { title: "Moby Dick", author: "Herman Melville", category: "Fiction" },
  { title: "To Kill a Mockingbird", author: "Harper Lee", category: "Fiction" },
  { title: "1984", author: "George Orwell", category: "Fiction" },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Fiction",
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    category: "Fiction",
  },
  {
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    category: "Fiction",
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    category: "Fiction",
  },
  { title: "Brave New World", author: "Aldous Huxley", category: "Fiction" },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    category: "Fiction",
  },
  {
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    category: "Fiction",
  },
  { title: "Fahrenheit 451", author: "Ray Bradbury", category: "Fiction" },
  { title: "Jane Eyre", author: "Charlotte Brontë", category: "Fiction" },
  { title: "Wuthering Heights", author: "Emily Brontë", category: "Fiction" },
  { title: "The Bell Jar", author: "Sylvia Plath", category: "Fiction" },
  { title: "Catch-22", author: "Joseph Heller", category: "Fiction" },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    category: "Fiction",
  },
  {
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    category: "Fiction",
  },
  {
    title: "The Fault in Our Stars",
    author: "John Green",
    category: "Fiction",
  },
  { title: "Little Women", author: "Louisa May Alcott", category: "Fiction" },
  {
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    category: "Fiction",
  },
  {
    title: "The Perks of Being a Wallflower",
    author: "Stephen Chbosky",
    category: "Fiction",
  },
  { title: "The Outsiders", author: "S.E. Hinton", category: "Fiction" },
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    category: "Memoir",
  },
  {
    title: "The Things They Carried",
    author: "Tim O'Brien",
    category: "Fiction",
  },
  { title: "The Road", author: "Cormac McCarthy", category: "Fiction" },
  {
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    category: "Fiction",
  },
  { title: "The Kite Runner", author: "Khaled Hosseini", category: "Fiction" },
  { title: "The Book Thief", author: "Markus Zusak", category: "Fiction" },
  { title: "The Lovely Bones", author: "Alice Sebold", category: "Fiction" },
  {
    title: "Gone with the Wind",
    author: "Margaret Mitchell",
    category: "Fiction",
  },
  {
    title: "The Time Traveler's Wife",
    author: "Audrey Niffenegger",
    category: "Fiction",
  },
  {
    title: "The Night Circus",
    author: "Erin Morgenstern",
    category: "Fiction",
  },
  { title: "The Light We Lost", author: "Jill Santopolo", category: "Fiction" },
  { title: "The Goldfinch", author: "Donna Tartt", category: "Fiction" },
  { title: "Life After Life", author: "Kate Atkinson", category: "Fiction" },
  { title: "The Nightingale", author: "Kristin Hannah", category: "Fiction" },
  {
    title: "The Song of Achilles",
    author: "Madeline Miller",
    category: "Fiction",
  },
  { title: "Circe", author: "Madeline Miller", category: "Fiction" },
  {
    title: "Eleanor Oliphant Is Completely Fine",
    author: "Gail Honeyman",
    category: "Fiction",
  },
  {
    title: "The House of the Spirits",
    author: "Isabel Allende",
    category: "Fiction",
  },
  {
    title: "The Light Between Oceans",
    author: "M.L. Stedman",
    category: "Fiction",
  },
  { title: "Anxious People", author: "Fredrik Backman", category: "Fiction" },
  { title: "The Midnight Library", author: "Matt Haig", category: "Fiction" },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    category: "Fiction",
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    category: "Fiction",
  },
  { title: "Normal People", author: "Sally Rooney", category: "Fiction" },
  { title: "The Vanishing Half", author: "Brit Bennett", category: "Fiction" },
  {
    title: "The Tattooist of Auschwitz",
    author: "Heather Morris",
    category: "Fiction",
  },
  { title: "The Guest List", author: "Lucy Foley", category: "Fiction" },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    category: "Fiction",
  },
  {
    title: "The Woman in the Window",
    author: "A.J. Finn",
    category: "Fiction",
  },
  {
    title: "The Couple Next Door",
    author: "Shari Lapena",
    category: "Fiction",
  },
  { title: "Behind Closed Doors", author: "B.A. Paris", category: "Fiction" },
  {
    title: "The Wife Between Us",
    author: "Greer Hendricks",
    category: "Fiction",
  },
  {
    title: "The Last Thing He Told Me",
    author: "Laura Dave",
    category: "Fiction",
  },
  { title: "The Family Upstairs", author: "Lisa Jewell", category: "Fiction" },
  {
    title: "The Book of Lost Names",
    author: "Kristin Harmel",
    category: "Fiction",
  },
  { title: "The Lying Game", author: "Ruth Ware", category: "Fiction" },
  { title: "The Chain", author: "Adrian McKinty", category: "Fiction" },
  { title: "The Woman in Cabin 10", author: "Ruth Ware", category: "Fiction" },
  { title: "Then She Was Gone", author: "Lisa Jewell", category: "Fiction" },
  {
    title: "The Perfect Couple",
    author: "Elin Hilderbrand",
    category: "Fiction",
  },
  { title: "The Wife Upstairs", author: "Rachel Hawkins", category: "Fiction" },
  { title: "The Guest Book", author: "Sarah Blake", category: "Fiction" },
  { title: "The Dutch House", author: "Ann Patchett", category: "Fiction" },
  {
    title: "The Book of Longings",
    author: "Sue Monk Kidd",
    category: "Fiction",
  },
  {
    title: "The Night Watchman",
    author: "Louise Erdrich",
    category: "Fiction",
  },
  { title: "A Man Called Ove", author: "Fredrik Backman", category: "Fiction" },
  { title: "The Overstory", author: "Richard Powers", category: "Fiction" },
  {
    title: "The Underground Railroad",
    author: "Colson Whitehead",
    category: "Fiction",
  },
  {
    title: "The Water Dancer",
    author: "Ta-Nehisi Coates",
    category: "Fiction",
  },
  {
    title: "The 100-Year-Old Man Who Climbed Out the Window and Disappeared",
    author: "Jonas Jonasson",
    category: "Fiction",
  },
  { title: "The Henna Artist", author: "Alka Joshi", category: "Fiction" },
  {
    title: "The Last House on Needless Street",
    author: "Catriona Ward",
    category: "Fiction",
  },
  {
    title: "Malibu Rising",
    author: "Taylor Jenkins Reid",
    category: "Fiction",
  },
  {
    title: "The Paris Library",
    author: "Janet Skeslien Charles",
    category: "Fiction",
  },
  {
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    category: "Fiction",
  },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    category: "Fiction",
  },
];

export const get_data = () => {
  const uniqueData = data.filter(
    (item, index, self) =>
      index === self.findIndex((t) => t.title === item.title)
  );
  return uniqueData;
};
export const add_book = (book) => {
  data.push(book);
};
